services:
  db-auth-management:
    container_name: db-auth-management
    hostname: db-auth-management
    image: docker.io/library/postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - pg-data:/var/lib/postgresql

  cache-auth-management:
    container_name: cache-auth-management
    hostname: cache-auth-management
    image: docker.io/library/memcached:latest
    ports:
      - "11211:11211"
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
volumes:
  pg-data:
